import crypto from "node:crypto";

const now = () => new Date().toISOString();
const plusHours = (hours) => new Date(Date.now() + hours * 60 * 60 * 1000).toISOString();

export const dev = {
  users: [
    {
      id: "user-current",
      telegram_id: "100001",
      username: "simon_founder",
      first_name: "Симон",
      last_name: "Бедункевич",
      role: "Основатель",
      looking_for: "Пилотные клиенты, партнерства, B2B продажи",
      can_help_with: "AI MVP, продукт, go-to-market",
      looking_for_tags: ["пилоты", "b2b", "партнерства"],
      can_help_with_tags: ["ai", "mvp", "продукт"],
      company: "FUP",
      field: "SaaS",
      is_visible: true,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: "user-2",
      telegram_id: "2002",
      username: "anna_vc",
      first_name: "Анна",
      last_name: "Смирнова",
      role: "Инвестор",
      looking_for: "Команды с ранней выручкой",
      can_help_with: "Fundraising, B2B intro, метрики",
      looking_for_tags: ["выручка", "saas"],
      can_help_with_tags: ["fundraising", "b2b", "intro"],
      company: "Northstar VC",
      field: "Venture",
      is_visible: true,
      created_at: now(),
      updated_at: now(),
    },
    {
      id: "user-3",
      telegram_id: "2003",
      username: "mikhail_growth",
      first_name: "Михаил",
      last_name: "Ильин",
      role: "Эксперт",
      looking_for: "B2B SaaS кейсы",
      can_help_with: "Growth loops, activation, retention",
      looking_for_tags: ["saas", "retention"],
      can_help_with_tags: ["growth", "activation", "b2b"],
      company: "Growth Desk",
      field: "Growth",
      is_visible: true,
      created_at: now(),
      updated_at: now(),
    },
  ],
  organizations: [{ id: "org-1", name: "FUP Labs", created_at: now() }],
  organization_members: [{ id: "om-1", organization_id: "org-1", user_id: "user-current", role: "owner" }],
  events: [
    {
      id: "event-1",
      organization_id: "org-1",
      organizer_id: "user-current",
      name: "Founder Demo Week",
      slug: "demo-fup-event",
      invite_code: "demo2026",
      description: "Demo event",
      starts_at: plusHours(-24),
      ends_at: plusHours(72),
      privacy: "invite_only",
      goals: ["followups", "meetings"],
      created_at: now(),
    },
  ],
  event_members: [
    { id: "em-1", event_id: "event-1", user_id: "user-current", status: "active", joined_at: now() },
    { id: "em-2", event_id: "event-1", user_id: "user-2", status: "active", joined_at: now() },
    { id: "em-3", event_id: "event-1", user_id: "user-3", status: "active", joined_at: now() },
  ],
  contacts: [],
  followups: [],
  reminders: [],
  outcomes: [],
  recommendations: [],
  analytics_events: [],
  bot_messages: [],
  reports: [],
};

export const id = (prefix) => `${prefix}_${crypto.randomUUID()}`;
export const timestamp = now;
